#ifndef __CONNECT_DEFINES_H__
#define __CONNECT_DEFINES_H__

// Server default info defines
#define SERVER_PORT 8080
#define SERVER_ADDR "127.0.0.1"
#define SERVER_CONNECTION_TIMEOUT_TRY_SEC 1
#define SERVER_CONNECTION_TRIES 5
#define RECEIVE_BUFFER_SIZE 128
#define RECEIVE_TIMEOUT_MS 10

#endif //__CONNECT_DEFINES_H__
